spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/edircabsan/spring-amq
          search-paths:
          - "config-properties/{application}/{profile}"
          - "config-properties/global/{profile}"